[workspace]
resolver = "2"

members = [
    "simulation",
    "terminal_renderer",
    "wasm-pack-renderer",
    "pixels_renderer",
]


[profile.release.package.wasm-pack-renderer]
# Tell `rustc` to optimize for small code size.
opt-level = "s"